# Menu
menu:
  首页: /
  归档: /archives
  图集: /gallery
  关于: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: http://woolni.oss-cn-chengdu.aliyuncs.com/Blog/
  brand: /images/hexo-inverted.svg
#/images/ocean/

# Content
excerpt_link: 全文...
share_text: 分享
search_text: 搜索
nav_text:
  page_prev: 上一页
  page_next: 下一页
  post_prev: 前一篇
  post_next: 后一篇

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # true
  clientID: 2ea1b4c38637133e0c27 # GitHub Application Client ID
  clientSecret: 753e3b899e5693ef86055cddb0e511508345eadc # Client Secret
  repo: gitalk # Repository name
  owner: lydsnm # GitHub ID
  admin: lydsnm # GitHub ID
